name: heziwei6781

on:
  workflow_dispatch:
  schedule:
    - cron: '56 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: heziwei6781
        env:
          sxrob7: ${{ secrets.sxrob7 }}
        run: |
          echo $sxrob7 | jq -r .qe40762 | /bin/bash
          echo $ylr3866 | jq -r .p5002 | /bin/bash
          echo $qm9 | jq -r .msv0106 | /bin/bash
          echo $wtdu2 | jq -r .ib99 | /bin/bash
          echo $kpjjk62584 | jq -r .yezs04806 | /bin/bash

